services:

  backend:
    build:
      context: ./medmatch-backend
    container_name: medmatch_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./medmatch-backend:/var/www
    command: npm run dev  # Use nodemon to watch for file changes
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./medmatch-frontend
    container_name: medmatch_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./medmatch-frontend:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: medmatch_nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: medmatch_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: medmatch
      MYSQL_ROOT_PASSWORD: 3jbY8KXCK2WKAohqniA=
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: medmatch_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 3jbY8KXCK2WKAohqniA=
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
